name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t payment-gateway .

      - name: Log in to Amazon ECR
        uses: docker/login-action@v1
        with:
          ecr: auto
          logout: true
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Tag Docker image
        run: docker tag payment-gateway:latest ${{ secrets.AWS_ECR_REGISTRY }}/payment-gateway:latest

      - name: Push Docker image
        run: docker push ${{ secrets.AWS_ECR_REGISTRY }}/payment-gateway:latest
